package com.java;

public class Fibonacci {

	/**
	 * @param args
	 * 
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 
	 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 
	 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		/**
		 * 
		 * General method using for loop
		 * 
		 */
		try{
		long a=1,b=2;
		long sum=2;
		long c=0;
		while(c<4000000)
		{
			
		c=a+b;
		a=b;
		b=c;
		if(c%2==0 && c<4000000)
		{
		sum=sum+c;
		System.out.println("Fibo-sum:"+sum);
		}
		}
		}
		catch(Exception e)
		{
			System.out.println( e);
		}
		

	}

}
